name: nopch-build
on:
  push:
    branches:
      - 'npcbots_3.3.5'
      - 'CI'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-22.04
            compiler:
              CC: clang-15
              CXX: clang++-15
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
          - os: ubuntu-24.04
            compiler:
              CC: gcc-14
              CXX: g++-14
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler }}-nopch
    env:
      COMPILER: ${{ matrix.compiler }}
    if: github.repository == 'liyunfan1223/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          pch: false
