name: macos-build
on:
  push:
    branches: [ "Playerbot" ]
  pull_request:
    branches: [ "Playerbot" ]

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  macos-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/ccache
          key: ccache:${{ matrix.os }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.os }}:${{ github.ref }}
            ccache:${{ matrix.os }}
      - name: Install latest bash
        run: brew install bash
      - name: Configure OS
        run: source ./acore.sh install-deps
      - name: Build
        run: source ./apps/ci/mac/ci-compile.sh
